#!/usr/bin/bash

target=$1
src=$2

if [ $# -ne 2 ]; then
	echo "Error@nparams"
	exit 1
fi

# convert
if [[ ! -f $target ]] || [[ ! -f $src ]]; then
	echo "Error@file exist: $target or $src do not exist"
	exit 1
fi

out="out.bmp"
echo "" > $out
echo " [+] $out file created."

# fixed sizes
width=1222
heigth=1228

convert -resize "$width"x"$heigth"! $target $target.bmp
convert -resize "$width"x"$heigth"! $src $src.bmp

#exiftool $src.bmp
#exiftool $out

# LSB
./main.py $target.bmp $out $src.bmp

echo " [+] completed."

#display out.bmp